name: Secure Deploy to GitHub Pages
on:
  push:
    branches: ["main"]
  workflow_dispatch:

# Bloqueio global: Princípio de Privilégio Mínimo
permissions:
  contents: read
  pages: write
  id-token: write # Mandatório para isolamento via OIDC

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code hermético
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v4

      - name: Build & Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: OIDC Deploy to Pages
        id: deployment
        uses: actions/deploy-pages@v4
